Adds ability to pass options to simpleMDE
smith-carson/ember-simplemde pull request #5
Opened 2017-05-03 18:45 UTC by Duder-onomy

* Updates readme with examples and instructions around options
* Adds new public options parameter to the simple-mde component
* Updates simple-mde component to merge instance options into global options into default (internal) simple-mde options before creating the instance
* Adds example to the dummy app to show usage of instance options
* Adds integration test for disabling the simple-mde toolbar via options parameter

2017-05-03 21:03 UTC, Duder-onomy commented
Actually, dont merge this yet. 
SimpleMDE needs its global in the namespace to assign custom toolbar support. 
If you look at the custom toolbar stuff: 
https://github.com/NextStepWebs/simplemde-markdown-editor#toolbar-icons

Im gonna make another commit now with a workaround... Looking forward to see what you think.

2017-05-03 21:18 UTC, Duder-onomy commented
Ok, I added support for toolbar actions to be expressed as strings and unpacked against the window.

2017-05-04 20:56 UTC, wuarmin commented
Great PR!

2017-05-26 14:28 UTC, marceloandrader requested changes
@Duder-onomy  I'd like to close this PR, could you just add a sample for the toolbar functions then I will merge it.

2017-05-26 14:28 UTC, marceloandrader commented on addon/components/simple-mde.js
> +  unpackToolbarOption: function(toolbarOption) {
@Duder-onomy  can you put some sample on how to use this, please?

2017-06-14 20:33 UTC, malatin3 commented
Any chance of getting this closed out soon? I'd love to start using this but the ability to set options is holding me back.

2017-06-14 21:01 UTC, marceloandrader commented
I just needed a sample for the toolbar option methods. And. I'll merge it.

On Wed, Jun 14, 2017, 15:33 Gregory Malatino <notifications@github.com>
wrote:

> Any chance of getting this closed out soon? I'd love to start using this
> but the ability to set options is holding me back.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/smith-carson/ember-simplemde/pull/5#issuecomment-308549810>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AADg0BW2oOPanoyh2bRZVCZ8ynmZG1owks5sEEOFgaJpZM4NPzK7>
> .
>

2017-06-16 00:14 UTC, Duder-onomy commented
Just saw this. Sorry guys, I will add an example of the toolbar options right now. 
Basically, simpleMde requires you to use function references from the global `window.simpleMde`when defining toolbar click handlers, but if we want to define handlers in the ember config, then we cannot reference these functions in the same way. 

I added code to unpack these funciton references when the simpleMde component inits. So if you had, `simpleMde.getTheThing.twice` as a toolbar button click handler in your config, we will unpack that against the window like `window.simpleMde.getTheThing.twice`. Basically, you can express function references as strings in your config which will be unpacked against the window when simpleMde tries to init. 

Hope that makes sense. I will update the PR right now.

2017-06-16 01:10 UTC, Duder-onomy commented
Added more notes and more examples. Please let me know if there is anything else I can do.

2017-06-16 14:21 UTC, merged

2017-06-16 14:25 UTC, marceloandrader commented
thank you @Duder-onomy  it's merged, I'll publish a new version.

2017-06-16 14:29 UTC, marceloandrader commented
Published in 1.1.0